
# fooparsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'statementSTORE LOAD JUMP NO_OPERATION MOVE REGISTER_NUMBER LABEL_REFERENCE LABEL_DEFINITION REFERENCE_DIR WORD_FILL_DIR HEX_LITERAL2 HEX_LITERAL4 COMMA DECIMAL_LITERAL BRANCH BRANCH_C BRANCH_O BRANCH_N BRANCH_Z ADD_NORMAL ADD_CARRY SUB_NORMAL SUB_CARRY SHIFT_LEFT SHIFT_RIGHT_LOGICAL SHIFT_RIGHT_ARITHMETIC ROTATE_RIGHT_ARITHMETIC ROTATE_RIGHT ROTATE_LEFT AND_LOGICAL OR_LOGICAL XOR_LOGICAL NOT_LOGICAL LOAD_LOW LOAD_HIGH NEWLINEstatement : REFERENCE_DIR LABEL_REFERENCE NEWLINEstatement : LOAD REGISTER_NUMBER REGISTER_NUMBER HEX_LITERAL2 NEWLINEstatement : STORE REGISTER_NUMBER REGISTER_NUMBER HEX_LITERAL2 NEWLINEempty :'
    
_lr_action_items = {'REGISTER_NUMBER':([1,2,5,6,],[5,6,8,9,]),'$end':([3,10,13,14,],[0,-1,-2,-3,]),'LABEL_REFERENCE':([4,],[7,]),'STORE':([0,],[2,]),'LOAD':([0,],[1,]),'REFERENCE_DIR':([0,],[4,]),'NEWLINE':([7,11,12,],[10,13,14,]),'HEX_LITERAL2':([8,9,],[11,12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> REFERENCE_DIR LABEL_REFERENCE NEWLINE','statement',3,'p_statement_ref','main.py',115),
  ('statement -> LOAD REGISTER_NUMBER REGISTER_NUMBER HEX_LITERAL2 NEWLINE','statement',5,'p_statement_load','main.py',120),
  ('statement -> STORE REGISTER_NUMBER REGISTER_NUMBER HEX_LITERAL2 NEWLINE','statement',5,'p_statement_store','main.py',125),
  ('empty -> <empty>','empty',0,'p_empty','main.py',133),
]
